name: $(BuildID)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

resources:
  - repo: self
    clean: true

jobs:
  ### Windows build ###
  - job: WINDOWS
    displayName: Windows
    strategy:
      # Change maxParallel to 1 make builds run in serial rather than in parallel
      maxParallel: 100
      matrix:
        .Net Core 3.1:
          FRAMEWORK: netcoreapp3.1

    condition: succeeded()
    pool:
      name: Hosted VS2017
      timeoutInMinutes: 180
    steps:
      - powershell: dotnet list .\azureiot.sln package --outdated
