name: $(BuildID)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
    - docs/*
    - tools/CaptureLogs/*
    - iothub/device/devdoc/*
    - iothub/service/devdoc/*

resources:
  - repo: self
    clean: true

jobs:
  ### Windows build ###
  - job: WINDOWS
    displayName: Windows
    strategy:
      # Change maxParallel to 1 make builds run in serial rather than in parallel
      maxParallel: 100
      matrix:
        .Net Core 3.1:
          FRAMEWORK: netcoreapp3.1
        .Net Core 2.1.18:
          FRAMEWORK: netcoreapp2.1.18
        .Net Framework 4.7.2:
          FRAMEWORK: net472
        .Net Framework 4.5.1:
          FRAMEWORK: net451

    condition: succeeded()
    pool:
      name: Hosted VS2017
      timeoutInMinutes: 180
    steps:
      - powershell: dotnet list package --outdated --include-prerelease        
